### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by rreitmann** [YousefED/ElasticUI#60]
Hi,

I am trying to setup your demo but I get the following error on page load:
TypeError: Cannot read property 'replace' of undefined
    at d.link.pre (http://rawgit.com/YousefED/ElasticUI/master/dist/elasticui.min.js:5:17870)
    at nodeLinkFn (https://code.angularjs.org/1.2.16/angular.js:6559:13)
    at compositeLinkFn (https://code.angularjs.org/1.2.16/angular.js:5986:15)
    at compositeLinkFn (https://code.angularjs.org/1.2.16/angular.js:5989:13)
    at compositeLinkFn (https://code.angularjs.org/1.2.16/angular.js:5989:13)
    at compositeLinkFn (https://code.angularjs.org/1.2.16/angular.js:5989:13)
    at nodeLinkFn (https://code.angularjs.org/1.2.16/angular.js:6573:24)
    at compositeLinkFn (https://code.angularjs.org/1.2.16/angular.js:5986:15)
    at publicLinkFn (https://code.angularjs.org/1.2.16/angular.js:5891:30)
    at https://code.angularjs.org/1.2.16/angular.js:1384:27 <eui-singleselect field="scaleLevel" size="5" class="ng-scope">

Do you have any idea what the reason might be?

**Comment by YousefED** [comment]
Hmm I have no issues here. Did you follow all the "ACTION" items?

Also, could you change it to use elasticui.js (instead of elasticui.min.js) and give another stacktrace?

**Comment by rreitmann** [comment]
Hi,

I have decided to use elasticsearch.angular.js directly but thanks for your input :-)
